// mockEquipmentData.ts
import type { EquipmentData } from "../Asset/Asset";// ajusta la ruta según tu proyecto

export const mockEquipmentData: EquipmentData[] = [
    // Santiago
    {
        tag: 'EQ-SCL-001',
        codigoCEN: 'CEN-8801',
        codigoSAP: 'SAP-1001',
        codigoNEMA: 'NEMA-A1',
        estado: 'Operativo',
        marca: 'Siemens',
        modelo: 'S7-1200',
        serie: 'SN123456',
        anoAntiguedad: 5,
        familia: 'Control',
        empresa: 'Empresa A',
        subestacion: 'Subestación Las Condes',
        latitud: -33.4145,
        longitud: -70.5956,
        observaciones: 'Equipo crítico para operación diaria',
        tensionCod: '13.8kV',
        corriente: '400A',
        anoFabricacion: 2019,
        bil: '125kV',
        tipo: 'PLC',
    },
    {
        tag: 'EQ-SCL-002',
        codigoCEN: 'CEN-8802',
        codigoSAP: 'SAP-1002',
        codigoNEMA: 'NEMA-A2',
        estado: 'En mantenimiento',
        marca: 'ABB',
        modelo: 'Relay RX',
        serie: 'SN789012',
        anoAntiguedad: 3,
        familia: 'Protección',
        empresa: 'Empresa A',
        subestacion: 'Subestación Vitacura',
        latitud: -33.4021,
        longitud: -70.5742,
        observaciones: 'Revisión programada Q3',
        tensionCod: '13.8kV',
        corriente: '400A',
        anoFabricacion: 2021,
        bil: '125kV',
        tipo: 'Relé',
    },
    {
        tag: 'EQ-SCL-003',
        codigoCEN: 'CEN-8803',
        codigoSAP: 'SAP-1003',
        codigoNEMA: 'NEMA-B1',
        estado: 'Operativo',
        marca: 'Schneider',
        modelo: 'PowerLogic',
        serie: 'SN345678',
        anoAntiguedad: 7,
        familia: 'Medición',
        empresa: 'Empresa B',
        subestacion: 'Subestación La Florida',
        latitud: -33.5609,
        longitud: -70.5789,
        observaciones: '',
        tensionCod: '0.4kV',
        corriente: '1000A',
        anoFabricacion: 2017,
        bil: '75kV',
        tipo: 'Medidor',
    },

    // Valparaíso
    {
        tag: 'EQ-VAP-001',
        codigoCEN: 'CEN-9001',
        codigoSAP: 'SAP-2001',
        codigoNEMA: 'NEMA-C1',
        estado: 'Operativo',
        marca: 'GE',
        modelo: 'Multilin',
        serie: 'SN901234',
        anoAntiguedad: 4,
        familia: 'Protección',
        empresa: 'Empresa C',
        subestacion: 'Subestación Valparaíso Centro',
        latitud: -33.0472,
        longitud: -71.6127,
        observaciones: 'Zona costera – inspección anual',
        tensionCod: '23kV',
        corriente: '300A',
        anoFabricacion: 2020,
        bil: '170kV',
        tipo: 'Relé',
    },

    // Concepción
    {
        tag: 'EQ-CCP-001',
        codigoCEN: 'CEN-9101',
        codigoSAP: 'SAP-3001',
        codigoNEMA: 'NEMA-D1',
        estado: 'Operativo',
        marca: 'Eaton',
        modelo: 'Breaker X',
        serie: 'SN567890',
        anoAntiguedad: 6,
        familia: 'Interruptor',
        empresa: 'Empresa A',
        subestacion: 'Subestación Concepción Norte',
        latitud: -36.8269,
        longitud: -73.0498,
        observaciones: 'Alta carga en verano',
        tensionCod: '13.8kV',
        corriente: '600A',
        anoFabricacion: 2018,
        bil: '125kV',
        tipo: 'Interruptor',
    },

    // Antofagasta
    {
        tag: 'EQ-ANT-001',
        codigoCEN: 'CEN-9201',
        codigoSAP: 'SAP-4001',
        codigoNEMA: 'NEMA-E1',
        estado: 'Operativo',
        marca: 'Rockwell',
        modelo: 'CompactLogix',
        serie: 'SN112233',
        anoAntiguedad: 2,
        familia: 'Control',
        empresa: 'Empresa D',
        subestacion: 'Subestación Minera Antofagasta',
        latitud: -23.6525,
        longitud: -70.3954,
        observaciones: 'Ambiente árido – sellado especial',
        tensionCod: '4.16kV',
        corriente: '800A',
        anoFabricacion: 2022,
        bil: '95kV',
        tipo: 'PLC',
    },

    // Temuco
    {
        tag: 'EQ-TMC-001',
        codigoCEN: 'CEN-9301',
        codigoSAP: 'SAP-5001',
        codigoNEMA: 'NEMA-F1',
        estado: 'En mantenimiento',
        marca: 'Siemens',
        modelo: 'S7-1500',
        serie: 'SN445566',
        anoAntiguedad: 1,
        familia: 'Control',
        empresa: 'Empresa B',
        subestacion: 'Subestación Temuco Sur',
        latitud: -38.7396,
        longitud: -72.5903,
        observaciones: 'Instalación reciente',
        tensionCod: '13.8kV',
        corriente: '400A',
        anoFabricacion: 2023,
        bil: '125kV',
        tipo: 'PLC',
    },

    // Puerto Montt
    {
        tag: '52E630A0049',
        codigoCEN: 'CEN-9401',
        codigoSAP: 'SAP-6001',
        codigoNEMA: 'NEMA-G1',
        estado: 'Operativo',
        marca: 'ABB',
        modelo: 'MicroSCADA',
        serie: 'SN778899',
        anoAntiguedad: 8,
        familia: 'SCADA',
        empresa: 'Empresa C',
        subestacion: 'Subestación Puerto Montt',
        latitud: -41.4718,
        longitud: -72.9424,
        observaciones: 'Sistema de monitoreo remoto',
        tensionCod: '23kV',
        corriente: '300A',
        anoFabricacion: 2016,
        bil: '170kV',
        tipo: 'SCADA',
    },

    // Iquique
    {
        tag: 'EQ-IQQ-001',
        codigoCEN: 'CEN-9501',
        codigoSAP: 'SAP-7001',
        codigoNEMA: 'NEMA-H1',
        estado: 'Operativo',
        marca: 'Schneider',
        modelo: 'Easergy',
        serie: 'SN101010',
        anoAntiguedad: 5,
        familia: 'Protección',
        empresa: 'Empresa D',
        subestacion: 'Subestación Zona Franca Iquique',
        latitud: -20.2307,
        longitud: -70.1357,
        observaciones: 'Alta humedad – mantenimiento mensual',
        tensionCod: '13.8kV',
        corriente: '400A',
        anoFabricacion: 2019,
        bil: '125kV',
        tipo: 'Relé',
    },

    // Punta Arenas
    {
        tag: 'EQ-PUQ-001',
        codigoCEN: 'CEN-9601',
        codigoSAP: 'SAP-8001',
        codigoNEMA: 'NEMA-I1',
        estado: 'Operativo',
        marca: 'GE',
        modelo: 'F650',
        serie: 'SN202020',
        anoAntiguedad: 9,
        familia: 'Protección',
        empresa: 'Empresa A',
        subestacion: 'Subestación Punta Arenas',
        latitud: -53.1638,
        longitud: -70.9178,
        observaciones: 'Condiciones extremas – calefacción integrada',
        tensionCod: '23kV',
        corriente: '300A',
        anoFabricacion: 2015,
        bil: '170kV',
        tipo: 'Relé',
    },
];